/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IOsmiumPolicyEngine {
    function init() external;

    function admin() external view returns (address);

    function nextPolicyId() external view returns (uint256);

    function registerMerchant(address merchant_address, bytes32 category, bytes32 metadata_hash) external;

    function setMerchantStatus(address merchant_address, bool active) external;

    function getMerchant(address merchant_address) external view returns (bool, bytes32, bytes32);

    function createPolicy(address agent, address token, uint256 max_per_tx, uint256 period_limit, uint64 period_seconds, uint64 valid_until) external returns (uint256);

    function setPolicyStatus(uint256 policy_id, bool active) external;

    function approveIntent(uint256 policy_id, bytes32 intent_hash, bytes32 context_hash, uint256 max_amount, uint64 valid_until) external;

    function revokeIntent(uint256 policy_id, bytes32 intent_hash) external;

    function getIntent(bytes32 intent_hash) external view returns (uint256, bytes32, uint256, uint64, bool);

    function getPolicy(uint256 policy_id) external view returns (address, address, address, uint256, uint256, uint64, uint64, bool);

    function currentPeriod(uint256 policy_id) external view returns (uint64, uint256);

    function previewAuthorization(uint256 policy_id, address agent, address merchant, address token, uint256 amount, bytes32 payment_id, bytes32 receipt_hash) external view returns (bool, uint8);

    function previewAuthorizationWithIntent(uint256 policy_id, bytes32 intent_hash, address agent, address merchant, address token, uint256 amount, bytes32 payment_id, bytes32 receipt_hash) external view returns (bool, uint8);

    function authorizePayment(uint256 policy_id, address merchant, address token, uint256 amount, bytes32 payment_id, bytes32 receipt_hash) external returns (bool);

    function authorizePaymentWithIntent(uint256 policy_id, bytes32 intent_hash, address merchant, address token, uint256 amount, bytes32 payment_id, bytes32 receipt_hash) external returns (bool);

    function getReceipt(bytes32 payment_id) external view returns (uint256, bytes32, address, address, uint256, bytes32, uint64);
}
